site_name: preonboarding
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/wanted-team6/preonboarding-boilerplate
site_dir: site
copyright: Copyright &copy; 2020, <a href="hhttps://github.com/wanted-team6/preonboarding-boilerplate</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
