#!/bin/sh

set -e

python wait_for_postgres.py
python manage.py migrate
# python manage.py dummy
python manage.py collectstatic --noinput

gunicorn --bind 0.0.0.0:8000 --access-logfile '-' --error-logfile '-' --capture-output --timeout 90 apps.wsgi:application
