version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}


services:
  postgres:
    restart: always
    image: "${ECR_REPOSITORY_URI}/postgres:latest"
    build:
      context: ../../
      dockerfile: docker/images/prod/Postgres.Dockerfile
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ../../.envs/.prod.postgres
    ports:
      - "5432:5432"

  nginx:
    restart: always
    image: "${ECR_REPOSITORY_URI}/nginx:latest"
    build:
      context: ../../
      dockerfile: docker/images/prod/Nginx.Dockerfile
    environment:
      - API_HOST=3.37.216.214
    ports:
      - "80:80"



  django:
    restart: always
    image: "${ECR_REPOSITORY_URI}/django:latest"
    environment:
      - DJANGO_SECRET_KEY=prod
    build:
      context: ../../
      dockerfile: docker/images/prod/Django.Dockerfile
    container_name: django
    env_file:
      - ../../.envs/.prod.django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command:
      - /start

  # documentation:
  #   restart: always
  #   build:
  #     context: ../../
  #     dockerfile: docker/images/local/Django.Dockerfile
  #   command: "mkdocs serve"
  #   volumes:
  #     - ../../:/code
  #   ports:
  #     - "8001:8001"
