# Generated by Django 3.2.9 on 2021-11-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='company_info.company')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='company_info.language')),
            ],
            options={
                'db_table': 'company_names',
            },
        ),
    ]
